name: CwCrop
author: mario_fischer
category: Widgets
tags: [images, crop, pictures, image]
demo: http://www.chipwreck.de/blog/software/cwcrop/cwcrop-demo/
docs: http://www.chipwreck.de/blog/software/cwcrop/help/

